# THIS IS THE REQUIRED NAME FIELD. 
# It should match your project folder name, using underscores.
name: flashcard_quiz_app
description: "A new Flutter project for a flashcard quiz app."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is good practice for private apps.
publish_to: 'none' # Remove this line if you plan to publish the app.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' # Adjust this to your Flutter SDK version if needed

dependencies:
  flutter:
    sdk: flutter

  # Your database packages
  sqflite: ^2.3.0
  path: ^1.8.3
  flip_card: ^0.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true