# pubspec.yaml (Corrected Version)

name: flashcard_quiz_app
description: "A new Flutter project for a flashcard quiz app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3
  flip_card: ^0.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # --- PACKAGE MOVED HERE ---
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # --- ASSETS SECTION FIXED AND CORRECTLY INDENTED ---
  assets:
    - assets/images/ # Be specific with the folder path for clarity

# --- THIS ENTIRE SECTION IS NEW, ADDED AT THE END, WITH NO INDENTATION ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # --- PATH CORRECTED: Use forward slashes and a PNG file for best quality ---
  image_path: "assets/images/Quizicon.ico"
  min_sdk_android: 21